"""add order_number to quote_requests

Revision ID: 5ef7e4d6801d
Revises: 56c618dd083a
Create Date: 2026-08-16 13:10:13.438986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef7e4d6801d'
down_revision: Union[str, None] = '56c618dd083a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('quote_requests', sa.Column('order_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quote_requests_order_number'), 'quote_requests', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_requests_order_number'), table_name='quote_requests')
    op.drop_column('quote_requests', 'order_number')
    op.drop_column('brands', 'logo_url')
    # ### end Alembic commands ###
