"""add site_settings

Revision ID: 8efb2a3438d1
Revises: 59b2521e86f1
Create Date: 2026-07-04 00:53:40.011979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efb2a3438d1'
down_revision: Union[str, None] = '59b2521e86f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_enabled', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('currencies', sa.JSON(), nullable=False),
    sa.Column('default_currency', sa.Text(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('default_language', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
