"""Add parent_id to categories for subcategory support

Revision ID: 9c0ba879f9db
Revises: 56a3fd8f5552
Create Date: 2026-06-21 03:22:32.121449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c0ba879f9db'
down_revision: Union[str, None] = '56a3fd8f5552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add slug as nullable first (existing rows have no value yet)
    op.add_column('categories', sa.Column('slug', sa.String(length=120), nullable=True))
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint('categories_name_key', 'categories', type_='unique')

    # 2. Backfill slug from name for existing rows: lowercase, spaces/non-alnum -> hyphens
    op.execute("""
        UPDATE categories
        SET slug = trim(both '-' from regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g'))
        WHERE slug IS NULL
    """)

    # 2b. Resolve any duplicate slugs produced by the backfill (e.g. two categories
    # with similar names) by appending the row id, so the unique index below succeeds.
    op.execute("""
        WITH duplicates AS (
            SELECT id, slug,
                   ROW_NUMBER() OVER (PARTITION BY slug ORDER BY id) AS rn
            FROM categories
        )
        UPDATE categories
        SET slug = categories.slug || '-' || duplicates.id
        FROM duplicates
        WHERE categories.id = duplicates.id AND duplicates.rn > 1
    """)

    # 3. Now safe to enforce NOT NULL and uniqueness
    op.alter_column('categories', 'slug', nullable=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.drop_column('products', 'specs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('specs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.drop_column('categories', 'parent_id')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###