"""add customer ban fields

Revision ID: aa4f49d9f8cb
Revises: 94da755c0362
Create Date: 2026-07-02 07:54:13.708744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4f49d9f8cb'
down_revision: Union[str, None] = '94da755c0362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.text('false')))   
    op.add_column('customers', sa.Column('ban_reason', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('banned_at', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('banned_by_admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'admin_users', ['banned_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'banned_by_admin_id')
    op.drop_column('customers', 'banned_at')
    op.drop_column('customers', 'ban_reason')
    op.drop_column('customers', 'is_banned')
    # ### end Alembic commands ###
