"""add delivery_agencies table

Revision ID: e6c497207fa0
Revises: 94cdf1f7fb7e
Create Date: 2026-08-16 18:55:33.104168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c497207fa0'
down_revision: Union[str, None] = '94cdf1f7fb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quote_requests_order_number_key', 'quote_requests', type_='unique')
    op.create_index(op.f('ix_quote_requests_order_number'), 'quote_requests', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_requests_order_number'), table_name='quote_requests')
    op.create_unique_constraint('quote_requests_order_number_key', 'quote_requests', ['order_number'])
    # ### end Alembic commands ###
